service: auth-nest-lambda

provider:
  name: aws
  runtime: nodejs18.x

functions:
  auth:
    handler: src/adapters/controllers/auth.lambdaHandler
    events:
      - http:
          path: v1/auth/login/anonymous
          method: post
      - http:
          path: v1/auth/login
          method: post
      - http:
          path: v1/auth/register
          method: post
