service: auth-nest-lambda

provider:
  name: aws
  runtime: nodejs18.x
  stage: "v1"

plugins:
  - serverless-offline

functions:
  auth:
    timeout: 10
    handler: dist/main.handler
    events:
      - http:
          path: /auth/login/anonymous
          method: post
      - http:
          path: /auth/login
          method: post
      - http:
          path: /auth/register
          method: post
      - http:
          path: /doc
          method: get